DELETE http://localhost:5000/api/contact/2


###
GET http://localhost:5000/api/contacts


###
POST http://localhost:5000/api/contact
Content-Type: application/json

{
    "name":"John Doe",
    "number": "123-456-7890"
}44


###
OPTIONS http://localhost:5000/api/contact/1


###
PUT http://localhost:5000/api/contact/6377b6a2d0a10133dc2f9397
Content-Type: application/json

{
    "name":"John Doe",
    "number": "123-456-7890"
}