DELETE http://localhost:5000/api/contact/2


###
GET http://localhost:5000/api/contacts


###
POST http://localhost:5000/api/contact
Content-Type: application/json

{
    "name": "",
    "number": "12-43-234345"
}


###
OPTIONS http://localhost:5000/api/contact/1